get_filename_component(_ispmv_prefix "${CMAKE_CURRENT_LIST_DIR}/../../.." ABSOLUTE)
set(ISpMV_FOUND TRUE)
set(ISpMV_runtime_FOUND TRUE)
foreach(_component IN LISTS ISpMV_FIND_COMPONENTS)
    if(NOT _component STREQUAL "runtime")
        set(ISpMV_${_component}_FOUND FALSE)
        if(ISpMV_FIND_REQUIRED_${_component})
            set(ISpMV_FOUND FALSE)
            set(ISpMV_NOT_FOUND_MESSAGE "The binary SDK contains only the runtime component")
        endif()
    endif()
endforeach()
if(NOT EXISTS "${_ispmv_prefix}/lib/libispmv.so.1")
    set(ISpMV_FOUND FALSE)
    set(ISpMV_NOT_FOUND_MESSAGE "Extract the complete SDK: runtime library is missing")
endif()
if(ISpMV_FOUND AND NOT TARGET ISpMV::runtime)
    add_library(ISpMV::runtime SHARED IMPORTED)
    set_target_properties(ISpMV::runtime PROPERTIES
        IMPORTED_LOCATION "${_ispmv_prefix}/lib/libispmv.so.1"
        IMPORTED_SONAME "libispmv.so.1"
        INTERFACE_INCLUDE_DIRECTORIES "${_ispmv_prefix}/include")
endif()
unset(_component)
unset(_ispmv_prefix)
